spring:
  profiles:
    active: oauth2
  config:
    import: optional:file:.env[.properties]
  application:
    name: smash_rating
  datasource:
    url: jdbc:mysql://localhost:3306/smash_rating
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      default_batch_fetch_size: 1000
      jdbc:
        time_zone: Asia/Seoul
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.spatial.dialect.MySQL8SpatialDialect

  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}


springdoc:
  show-login-endpoint: true

jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}

server:
  port: ${PORT:8080}



---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
  sql:
    init:
      mode: never

  data:
    jpa:
      auditing:
        enabled: false

jwt:
  issuer: test_issuer
  secret: test_secret
