spring:
  config:
    import:
      - optional:file:.env[.properties]
      - "application-oauth2.yml"
  application:
    name: smash_rating
  jackson:
    property-naming-strategy: SNAKE_CASE

springdoc:
  show-login-endpoint: true

server:
  port: ${PORT:8080}

app:
  frontend:
    base-url: ${FRONTEND_URL:http://localhost:3000}

fcm:
  certification: fcm-certification.json

jwt:
  issuer: ${JWT_ISSUER:test_issuer}
  secret: ${JWT_SECRET:test_secret}


